<a href="https://colab.research.google.com/github/1Bur1/tuwaiq-h.w.-week8/blob/main/lab%2039%20Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
Day 39 Activity: Broadcasting
Tasks:
1) Normalize matrix by row using broadcasting
2) Verify each row has unit norm
"""

import numpy as np

# Provided matrix (edit if you want different values)
X = np.array([
    [3.0, 4.0],
    [1.0, 2.0],
    [0.0, 5.0],
])

# TODO: Compute row_norms and X_normalized
X = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])

row_means = X.mean(axis=1, keepdims=True)

col_means = X.mean(axis=0, keepdims=True)

X_centered_cols = X - col_means
# TODO: Print norms
print(row_means)
print(col_means)
print(X_centered_cols)

[[2.]
 [5.]
 [8.]]
[[4. 5. 6.]]
[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]
